theme: jekyll-theme-minimal
title: Welcome to all about George!
description: I am an aspring robotics engineer ![IMG_5889](https://user-images.githubusercontent.com/44282724/106854563-c577bf00-6678-11eb-84b4-d48e784e6ca6.JPG)

